import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "User Content and Conduct Policy | Nomyx Legal Documents",
  description: "Policy regarding acceptable user content and conduct on Nomyx.",
  alternates: {
    canonical: "https://www.nomyx.io/legal-documents/user-content-and-conduct-policy",
  },
};

export default function UserContentAndConductPolicyPage() {
  return (
    <article className="max-w-230 lg:ml-18">
      <header className="mb-8">
        <h1 className="mb-2 text-[32px] font-bold leading-tight text-ink md:text-[40px] md:leading-tight">
          Nomyx User Content and Conduct Policy
        </h1>
      </header>

      <div className="border-t border-border pt-9">
        <div className="space-y-8 text-[14px] font-normal leading-7 text-ink md:text-[16px] md:leading-7">
          
          <div className="space-y-4">
            <p>
              Nomyx provides a platform that allows our Subscribers and their End-Users to freely communicate and share content. The vast majority of the time this communication is productive and benefits the parties involved. However, there are times when a Subscriber or End-User takes advantage of the open nature of our Services to engage in or support objectionable or harmful conduct. We developed this Nomyx User Content and Conduct Policy (&quot;Policy&quot;) to make it clear that such activity is prohibited.
            </p>
            <p>
              The Policy is incorporated into the Nomyx Main Services Agreement (&quot;MSA&quot;) and applies to all Subscribers, Agents and End-Users who use the Services. Notwithstanding the terms of the MSA, Nomyx may, in its sole discretion, suspend or terminate an account immediately due to a violation of this Policy. Any person may report a violation of this Policy by reporting the violation using the form linked to above.
            </p>
            <p>
              We encourage all persons to report suspected violations of the Policy. There may be instances where we are limited in how we can respond to reported violations, but we want to know about this activity. If you have a copyright infringement complaint, please review and follow the process outlined in Nomyx&apos;s Copyright Infringement Notice and Takedown Policy. Nomyx may modify these policies at any time. Capitalized terms used in this Policy but not defined herein have the meaning given to them in the Nomyx MSA.
            </p>
          </div>

          <section className="space-y-5">
            <h2 className="text-[22px] font-bold leading-tight text-ink md:text-[24px]">
              1. Spam or Unwanted Contact
            </h2>
            <p>
              The Services may not be used to send or host spam, including the sending of unwanted or unauthorized commercial content, unwanted or mass solicitation, or other forms of duplicative or unsolicited messages.
            </p>
          </section>

          <section className="space-y-5">
            <h2 className="text-[22px] font-bold leading-tight text-ink md:text-[24px]">
              2. Illegal and Fraudulent Activities
            </h2>
            <p>
              The Services may not be used to engage in dangerous, illegal, or fraudulent activities or to directly or indirectly promote such activities. Please note that Nomyx is limited in its ability to review fraudulent activity that may occur outside of the Services or to assess the legality of certain activities and may require that persons work with law enforcement to validate the fraudulent nature or the illegality of the activity before we are able to take action related to a reported Account.
            </p>
          </section>

          <section className="space-y-5">
            <h2 className="text-[22px] font-bold leading-tight text-ink md:text-[24px]">
              3. Malicious Products and Activities
            </h2>
            <p>
              The Services may not be used to transmit viruses, malware, or other harmful code or content. This includes sending automated content or traffic, generated by bots or otherwise, that harms networks, services or other infrastructure of Nomyx or any third party.
            </p>
          </section>

          <section className="space-y-5">
            <h2 className="text-[22px] font-bold leading-tight text-ink md:text-[24px]">
              4. Hateful Activities
            </h2>
            <p>
              The Services may not be used to transmit or host hate speech, advocate violence or terrorism, distribute graphically violent or obscene content, or to support or normalize hateful, racist, libelous, or discriminatory activities. Further, use of the Services by organizations that promote or normalize hate against individuals, hateful speech, violence, terrorism or whose primary purpose is inciting hatred or violence, is prohibited. To effectively comply with this policy, organizations whose primary purpose is to host, promote or otherwise contain user-generated content (&quot;UGC&quot;) must implement reasonably effective moderation policies and remedial procedures related to UGC that would violate these prohibitions.
            </p>
          </section>

          <section className="space-y-5">
            <h2 className="text-[22px] font-bold leading-tight text-ink md:text-[24px]">
              5. Child Exploitation and Human Trafficking
            </h2>
            <p>
              Use of the Services for any content or activity that promotes or displays child sexual exploitation or abuse is prohibited. We will remove such content from the Service and take appropriate action. Further, uploading or sharing content that promotes, enables or discusses human trafficking is prohibited.
            </p>
          </section>

          <section className="space-y-5">
            <h2 className="text-[22px] font-bold leading-tight text-ink md:text-[24px]">
              6. Harassment and Bullying
            </h2>
            <p>
              The Services may not be used to engage in abusive, harassing, or bullying behavior, including when contacting Nomyx for customer support. This prohibition also includes a prohibition on illegal dissemination of private information or media using the Services.
            </p>
          </section>

          <section className="space-y-5">
            <h2 className="text-[22px] font-bold leading-tight text-ink md:text-[24px]">
              7. Deceptive Behavior and Account Hijacking
            </h2>
            <p>
              The Services may not be used to deceive individuals or impersonate third parties. Accessing another Account without the permission of the Subscriber that owns the Account is prohibited.
            </p>
          </section>

          <section className="space-y-5">
            <h2 className="text-[22px] font-bold leading-tight text-ink md:text-[24px]">
              8. Intellectual Property
            </h2>
            <p>
              You may not use the Services in a manner that infringes a third party&apos;s rights, including intellectual property rights. Additionally, if a primary purpose or result of your business is to infringe third parties&apos; intellectual property rights, then Nomyx reserves the right to suspend or terminate your Services, even if you do not use the Services directly for such infringement. Please note that Nomyx may be limited in its ability to assess alleged infringement that occurs outside of the Services, and may not be able to act on every report of alleged infringement.
            </p>
          </section>

        </div>
      </div>
    </article>
  );
}
